spring.application.name=estadisticas-deportivas


spring.datasource.url=jdbc:mysql://localhost:3306/sports_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080
